language: node_js
node_js:
  - "node"
sudo: false
cache:
  directories:
    - node_modules
branches:
  - master
notifications:
  email: true
deploy:
  provider: npm
  email: "robin@kearney.co.uk"
  api_key: $NPM_API_KEY
  on:
    tags: true
